services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
